export { createScanExecutorRegistrations } from './executors.ts'
export { artistMappingInputDigest, localWorkInputDigest, metadataInputDigest } from './digests.ts'
export { computeLocalWorkContentFingerprint } from './fingerprint.ts'
export { discoverBoundedLocalWorkCandidates } from './control-plane-discovery.ts'
export { ScanExecutorError } from './errors.ts'
export type { BoundedLocalWorkDiscoveryInput } from './control-plane-discovery.ts'
export type { LocalWorkCandidate, ScanDiscoveryLimits } from './discovery.ts'
export type { ScanExecutorConfig, ScanExecutorDependencies, ScanExecutionResult } from './types.ts'
