ALTER TYPE "ScanRunType" ADD VALUE IF NOT EXISTS 'LOCAL_IMPORT';
ALTER TYPE "ScanRunType" ADD VALUE IF NOT EXISTS 'LOCAL_CREATE';
ALTER TYPE "ScanRunType" ADD VALUE IF NOT EXISTS 'BATCH_IMPORT';

ALTER TYPE "ScanRunMode" ADD VALUE IF NOT EXISTS 'LOCAL_DIRECTORY_IMPORT';
ALTER TYPE "ScanRunMode" ADD VALUE IF NOT EXISTS 'LOCAL_CREATE';
ALTER TYPE "ScanRunMode" ADD VALUE IF NOT EXISTS 'BATCH_CREATE';
ALTER TYPE "ScanRunMode" ADD VALUE IF NOT EXISTS 'BATCH_REGISTER_IMAGES';
